version: "3"

services:
  middleware-service:
    container_name: middleware-service
    image: middleware-service
    networks:
      - db-network
    restart: unless-stopped
    ports:
      - 127.0.0.1:8881:8080
    environment:
      - "JAVA_OPTIONS=-XX:-OmitStackTraceInFastThrow -Dspring.profiles.active=local"
      - "SPRING_KAFKA_BOOTSTRAP_ADDRESS=kafka:9092"
      - "CORS_ALLOWED_ORIGINS=http://localhost:*, http://127.0.0.1:*, http://192.168.0.*:*, http://192.168.1.*:*, http://192.168.3.*:*"
      - "SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_ID=client"
      - "SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_SECRET=123456"
      - "SPRINGDOC_SWAGGER_UI_OAUTH_ENABLED=true"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://servicedb:5432/datasource_servicedb"
      - "SPRING_DATASOURCE_USERNAME=testuser"
      - "SPRING_DATASOURCE_PASSWORD=11111"
      - "SPRING_FLYWAY_LOCATIONS=classpath:db/migration/schema,classpath:db/migration/data/dev"
      - "SERVICE_MIDDLEWARE_INVENTORY_URL=http://localhost:8081/middleware-inventory"
    depends_on:
      - servicedb
    volumes:
      - ./log:/log


  middleware-inventory:
    container_name: middleware-inventory
    image: middleware-inventory
    networks:
      - db-network
    restart: unless-stopped
    ports:
      - 127.0.0.1:8882:8082
    environment:
      - "JAVA_OPTIONS=-XX:-OmitStackTraceInFastThrow -Dspring.profiles.active=local"
      - "SPRING_KAFKA_BOOTSTRAP_ADDRESS=kafka:9092"
      - "CORS_ALLOWED_ORIGINS=http://localhost:*, http://127.0.0.1:*, http://192.168.0.*:*, http://192.168.1.*:*, http://192.168.3.*:*"
      - "SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_ID=client"
      - "SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_SECRET=123456"
      - "SPRINGDOC_SWAGGER_UI_OAUTH_ENABLED=true"
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://inventorydb:5432/datasource_inventorydb"
      - "SPRING_DATASOURCE_USERNAME=testuser"
      - "SPRING_DATASOURCE_PASSWORD=11111"
      - "SPRING_FLYWAY_LOCATIONS=classpath:db/migration/schema,classpath:db/migration/data/dev"
      - "SERVICE_MIDDLEWARESERVICE_URL=http://middleware-service:8080/middleware-service" # Changed from localhost
    depends_on:
      - inventorydb
    volumes:
      - ./log:/log


networks:
  db-network:
    driver: bridge
