version: "3"

services:
  servicedb:
    image: postgres:16
    container_name: servicedb
    hostname: servicedb
    ports:
      - 127.0.0.1:5009:5432
    environment:
      - "POSTGRES_USER=testuser"
      - "POSTGRES_PASSWORD=11111"
      - "POSTGRES_DB=datasource_servicedb"
    networks:
      - db-network
    restart: always

  inventorydb:
      image: postgres:16
      container_name: inventorydb
      hostname: inventorydb
      ports:
        - 127.0.0.1:5010:5432
      environment:
        - "POSTGRES_USER=testuser"
        - "POSTGRES_PASSWORD=11111"
        - "POSTGRES_DB=datasource_inventorydb"
      networks:
        - db-network
      restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.0-1-ubi8
    container_name: zookeeper
    ports:
      - "127.0.0.1:2181:2181"
    environment:
      - "ZOOKEEPER_CLIENT_PORT=2181"
      - "ZOOKEEPER_TICK_TIME=2000"
    networks:
      - db-network

  kafka:
    image: confluentinc/cp-kafka:7.1.0-1-ubi8
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      - "KAFKA_BROKER_ID=1"
      - "KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9002"
      - "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT"
      - "KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT"
      - "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"
    networks:
      - db-network
networks:
  db-network:
    driver: bridge

